# Results

```{r}
library(cowplot)
library(magick)
library(jpeg)
library(grid)
library(ggplot2)
library(forcats)
```

```{r}
kill_1_erang = kill_stat %>%
  filter(match_id %in% agg_stat$match_id) %>%
  arrange(match_id, time)
```


```{r}
#TODO: scatter plot of total dead
kill<- kill_1_erang
dead<-kill%>%group_by(match_id)%>%arrange(time)%>%mutate(num = row_number())
dead1<-dead%>%group_by(num)%>%summarise(avg_time=mean(time))
ggplot(dead1,aes(x=avg_time,y=num))+geom_point()+
  xlab('Average time')+ylab('Death number') + ggtitle("Scatter plot of mean time to reach total dead")
ggplot(dead1,aes(x=log(avg_time),y=num))+geom_point()+
  xlab('log(Average time)')+ylab('Death number') + ggtitle("Scatter plot of log mean time to reach total dead")
```

```{r}
kill_1_erang = kill_1_erang %>%
  filter(killer_position_x >= 0 & killer_position_x <= 800000 & 
           killer_position_y >= 0 & killer_position_y <= 800000 &
           victim_position_x >= 0 & victim_position_x <= 800000 &
           victim_position_y >= 0 & victim_position_y <= 800000)
kill_1_erang$killer_position_x = kill_1_erang$killer_position_x*4096/800000
kill_1_erang$killer_position_y = kill_1_erang$killer_position_y*4096/800000
kill_1_erang$victim_position_x = kill_1_erang$victim_position_x*4096/800000
kill_1_erang$victim_position_y = kill_1_erang$victim_position_y*4096/800000

data_scaled = kill_1_erang %>% 
  select(c(killer_position_x, killer_position_y)) %>%
  drop_na(killer_position_x) %>% drop_na(killer_position_y)
```

```{r}
img <- readJPEG("erangel.jpg")
ggplot(data_scaled, aes(x=killer_position_x, y=killer_position_y)) +
  annotation_custom(rasterGrob(img, width=unit(1,"npc"), 
                height=unit(1,"npc"), interpolate = FALSE)
                , -Inf, Inf, -Inf, Inf) +
  geom_bin2d(alpha = 0.9, bins=100) +
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))+
  theme(axis.title=element_blank(),
        legend.position = "none")
```

```{r}
#TODO: kill by method
kill_by<-kill%>%group_by(killed_by)%>%summarize(num=n())%>%ungroup()
kill_by_above25000<-kill_by%>%filter(num>=25000)
ggplot(kill_by_above25000,aes(x=num,y=fct_reorder(killed_by,num)))+geom_point()+
  xlab('number')+ylab('method') + ggtitle("Cleveland dot plot of kill by method(count>=25000)")
kill_by_below25000<-kill_by%>%filter(num<25000)
ggplot(kill_by_below25000,aes(x=num,y=fct_reorder(killed_by,num)))+geom_point()+
  xlab('number')+ylab('method') + ggtitle("Cleveland dot plot of kill by method(count<25000)")
```

```{r}
#TODO: kill by method by different time frame

```

```{r}
#TODO: k/d analysis
kd <- agg_stat%>%mutate(ratio = player_kills/(player_dist_ride+player_dist_walk))
kd <- kd%>%filter(ratio<5)
ggplot(kd.5b,aes(x=ratio,y=team_placement))+geom_point(size=1, alpha = 0.3)+
  xlab('Kill ratio')+ylab('Team placement') + ggtitle("Scatter plot of team placement vs kill ratio")
```