# Interactive component

We now will analyze the dynamics of weapon use by different time frame<br>
To do that, we split the data set based on kills happened in eight time range.<br>
We create an iterative dot plot to demonstrate the behavior of kill by method counts in each time frame.

<br><br>

<script src="https://d3js.org/d3.v7.js"></script>


<div id="interaction1">

  <!-- Create interactive buttons -->
  <button onclick="update('t_0_125')">0-125 seconds</button>
  <button onclick="update('t_125_250')">125-250 seconds</button>
  <button onclick="update('t_250_375')">250-375 seconds</button>
  <button onclick="update('t_375_500')">375-500 seconds</button>
  <button onclick="update('t_500_750')">500-750 seconds</button>
  <button onclick="update('t_750_1000')">750-1000 seconds</button>
  <button onclick="update('t_1000_1500')">1000-1500 seconds</button>
  <button onclick="update('t_1500_2180')">1500-2180 seconds</button>


</div>

<script>

// create margin
var margin = {top: 30, right: 30, bottom: 80, left: 60},
    width = 800 - margin.left - margin.right,
    height = 350 - margin.top - margin.bottom;

// creat svg
var svg = d3.select("#interaction1")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform","translate(" + margin.left + "," + margin.top + ")");

// Initialize the axis
var x = d3.scaleBand()
  .range([ 0, width ])
  .padding(1);
  
var y = d3.scaleLinear()
  .range([ height, 0]);
var xAxis = svg.append("g")
  .attr("transform", "translate(0," + height + ")")

var yAxis = svg.append("g")
  .attr("class", "myYaxis")

svg.append("text")
        .attr("x", (width / 2))             
        .attr("y", 0 - (margin.top / 2))
        .attr("text-anchor", "middle")  
        .style("font-size", "16px") 
        .text("Kill by method in different time frame (High count method)");
        
svg.append("text")
    .attr("class", "x label")
    .attr("text-anchor", "end")
    .attr("x", width-50)
    .attr("y", height+60)
    .text("Kill by method");

svg.append("text")
    .attr("class", "y label")
    .attr("text-anchor", "end")
    .attr("y", 6)
    .attr("dy", ".75em")
    .attr("transform", "rotate(-90)")
    .text("count");   

function update(selectedVar) {
  // read data
  d3.csv("https://gist.githubusercontent.com/tthatyuwen/5c0094ed90840e977bf71071ee62d991/raw/62b65194d671a2d33a8dd1a509db711430dfe13a/kill_by_time_high.csv").then( function(data) {

    // add axis
    x.domain(data.map(function(d) { return d.killed_by; }))
    xAxis.call(d3.axisBottom(x))
    .selectAll("text")
    .style("text-anchor", "end")
    .attr("transform", "rotate(-75)")
    .attr("dx","-.8em")
    .attr("dy","-.5em")

    y.domain([0, 75000])//d3.max(data, function(d) { return +d[selectedVar] }) ]);
    yAxis.call(d3.axisLeft(y));

    // create line
    var l = svg.selectAll(".myLine")
      .data(data)
    // update lines
    l.enter()
      .append("line")
      .attr("class", "myLine")
      .merge(l)
      .transition()
      .duration(800)
        .attr("x1", function(d) { return x(d.killed_by); })
        .attr("x2", function(d) { return x(d.killed_by); })
        .attr("y1", y(0))
        .attr("y2", function(d) { return y(d[selectedVar]); })
        .attr("stroke", "grey")


    // create dot
    var c = svg.selectAll("circle")
      .data(data)
    c.enter()
      .append("circle")
      .merge(c)
      .transition()
      .duration(800)
        .attr("cx", function(d) { return x(d.killed_by); })
        .attr("cy", function(d) { return y(d[selectedVar]); })
        .attr("r", 5)
        .attr("fill", "lightblue");

  })

}

update('t_0_125')

</script>


<div id="interaction2">

  <!-- Create interactive buttons -->
  <button onclick="update1('t_0_125')">0-125 seconds</button>
  <button onclick="update1('t_125_250')">125-250 seconds</button>
  <button onclick="update1('t_250_375')">250-375 seconds</button>
  <button onclick="update1('t_375_500')">375-500 seconds</button>
  <button onclick="update1('t_500_750')">500-750 seconds</button>
  <button onclick="update1('t_750_1000')">750-1000 seconds</button>
  <button onclick="update1('t_1000_1500')">1000-1500 seconds</button>
  <button onclick="update1('t_1500_2180')">1500-2180 seconds</button>


</div>

<script>

// creat svg
var svg2 = d3.select("#interaction2")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform","translate(" + margin.left + "," + margin.top + ")");

// Initialize the axis
var x1 = d3.scaleBand()
  .range([ 0, width ])
  .padding(1);
var xAxis1 = svg2.append("g")
  .attr("transform", "translate(0," + height + ")")

var y1 = d3.scaleLinear()
  .range([ height, 0]);
var yAxis1 = svg2.append("g")
  .attr("class", "myYaxis1")


svg2.append("text")
        .attr("x", (width / 2))             
        .attr("y", 0 - (margin.top / 2))
        .attr("text-anchor", "middle")  
        .style("font-size", "16px") 
        .text("Kill by method in different time frame (Low count method)");

svg2.append("text")
    .attr("class", "x label")
    .attr("text-anchor", "end")
    .attr("x", width-50)
    .attr("y", height+60)
    .text("Kill by method");

svg2.append("text")
    .attr("class", "y label")
    .attr("text-anchor", "end")
    .attr("y", 6)
    .attr("dy", ".75em")
    .attr("transform", "rotate(-90)")
    .text("count");    


function update1(selectedVar) {
  // read data
  d3.csv("https://gist.githubusercontent.com/tthatyuwen/57c2c7a050b65109361848a23aa4f646/raw/0f8a1477386475ad0c635fd43a78724c6576ad00/kill_by_time_low.csv").then( function(data) {

    // add axis
    x1.domain(data.map(function(d) { return d.killed_by; }))
    xAxis1.call(d3.axisBottom(x1))
    .selectAll("text")
    .style("text-anchor", "end")
    .attr("transform", "rotate(-75)")
    .attr("dx","-.8em")
    .attr("dy","-.5em")

    y1.domain([0, 5000])
    yAxis1.call(d3.axisLeft(y1));

    // create line
    var l1 = svg2.selectAll(".myLine")
      .data(data)
    // update lines
    l1.enter()
      .append("line")
      .attr("class", "myLine")
      .merge(l1)
      .transition()
      .duration(800)
        .attr("x1", function(d) { return x1(d.killed_by); })
        .attr("x2", function(d) { return x1(d.killed_by); })
        .attr("y1", y1(0))
        .attr("y2", function(d) { return y1(d[selectedVar]); })
        .attr("stroke", "grey")


    // create dot
    var c1 = svg2.selectAll("circle")
      .data(data)
    c1.enter()
      .append("circle")
      .merge(c1)
      .transition()
      .duration(800)
        .attr("cx", function(d) { return x1(d.killed_by); })
        .attr("cy", function(d) { return y1(d[selectedVar]); })
        .attr("r", 5)
        .attr("fill", "lightblue");

  })

}

update1('t_0_125')

</script>

<br><br>
From the plots, we can clearly see that at the beginning of each game, the most popular weapons are S1895, Vector, or, interestingly, your fists.<br>
These are all great tools for close distance combat.<br>
Since resources are limited at the beginning of each game, players will use these weapons to knock out close enemies as fast as possible.<br>
As game proceeds, we can see that the plot moves gradually to favor popular weapons like M416 and SCAR-L. The graph also gets increasingly polarized, as popular weapons are used repeatedly and unpopular weapons are being left out more and more.
